# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - inventanalytics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_92020a27961c40ffa44f073fea2b3bce }}
        password: ${{ secrets.AzureAppService_ContainerPassword_519e5814b6ae4b9e96581de2d5fffe15 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_92020a27961c40ffa44f073fea2b3bce }}/inventanalytics:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'inventanalytics'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c14ff83a04514f7f8fb5418a2625616d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_92020a27961c40ffa44f073fea2b3bce }}/inventanalytics:${{ github.sha }}'